# Generated by Django 3.2.12 on 2023-06-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
