# Generated by Django 3.2.12 on 2023-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listings_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.CharField(default='active', max_length=8),
            preserve_default=False,
        ),
    ]
