# Generated by Django 3.2.12 on 2023-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listings_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commenting_listing', to='auctions.Comments'),
        ),
    ]
